# This file was generated by GoReleaser. DO NOT EDIT.
cask "squad-oc" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "5fece8e9b5e6d6a1d9ce4590120a419879fe77d175e28300cbf8d75d6e7d9493"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.7.0/squad-oc_0.7.0_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "660213bfce924af638a3ebdf6ae32447d172bdac425c835829ca9868d1dd1ac3"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.7.0/squad-oc_0.7.0_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "04fedc6eb0e03d54024b635b5a9d11b3ceda847894c4d93f0c2f4a9dafececb8"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.7.0/squad-oc_0.7.0_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c89e61e71a5c1c739868ec546bff28636c291d9892c725295a07c3499578b796"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.7.0/squad-oc_0.7.0_linux_amd64.tar.gz"
    end
  end

  name "squad-oc"
  desc "Human-led AI agent teams for OpenCode"
  homepage "https://github.com/xeaser/squad-opencode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squad-oc"

  # No zap stanza required

  caveats <<~EOS
    Existing installs from this tap as a formula migrate via tap_migrations.json.
  EOS
end
