# This file was generated by GoReleaser. DO NOT EDIT.
cask "squad-oc" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "d077da5e23ac0e16042d0a31252c3aa93c4bb5eb5135e5cbb052dbcee04523e3"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.9.0/squad-oc_0.9.0_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "62b0703d33a49b65c99d5a6bedb8d56aebb2493affbe9003df1dbef5ddd7442b"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.9.0/squad-oc_0.9.0_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d7b78cbac0c89df2e0d8fe2e4724321ea29a6483deceb0d8135c3f35d9883ffb"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.9.0/squad-oc_0.9.0_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20b3b22b9ffff5b23ab839c0253c9486a366a3c1d2dbe1091599420745202a83"
      url "https://github.com/xeaser/squad-opencode/releases/download/v0.9.0/squad-oc_0.9.0_linux_amd64.tar.gz"
    end
  end

  name "squad-oc"
  desc "Human-led AI agent teams for OpenCode"
  homepage "https://github.com/xeaser/squad-opencode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squad-oc"

  # No zap stanza required

  caveats <<~EOS
    Existing installs from this tap as a formula migrate via tap_migrations.json.
  EOS
end
