# This file was generated by GoReleaser. DO NOT EDIT.
cask "squad-oc" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "debe956ed271134a9779ebfc45ec66247d106b6caac3ffebc7e91c93fdcee1bb"
      url "https://github.com/xeaser/squad-opencode/releases/download/v#{version}/squad-oc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e6622f6e2d49560b141fb8fb7d235dd37a28e18915144a813acf0ed237fa4170"
      url "https://github.com/xeaser/squad-opencode/releases/download/v#{version}/squad-oc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "454df5d8c218078cf7336c5f038b88939fae9c1be651dcbd696d1c33a8d1d821"
      url "https://github.com/xeaser/squad-opencode/releases/download/v#{version}/squad-oc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dbd37b2712d0b1dc8e270248abdb007d0c2f6f61627286e9c263daf0d362310f"
      url "https://github.com/xeaser/squad-opencode/releases/download/v#{version}/squad-oc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "squad-oc"
  desc "Human-led AI agent teams for OpenCode"
  homepage "https://github.com/xeaser/squad-opencode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "squad-oc"

  # No zap stanza required
end
